#!/bin/bash

echo "📦 CÓMO USAR LA IMPORTACIÓN DE PRESTASHOP"
echo ""
echo "📍 UBICACIÓN:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Página: CATÁLOGO (no Configuración)"
echo "✅ Sección: '2. Conectar Ecommerce'"
echo ""
echo "🔧 PASOS PARA IMPORTAR:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Ve a la página CATÁLOGO"
echo "   (no Configuración)"
echo ""
echo "2️⃣  Busca la sección '2. Conectar Ecommerce'"
echo ""
echo "3️⃣  Crea/Configura una conexión PrestaShop:"
echo "   - Haz clic en 'Agregar Conexión' o edita una existente"
echo "   - Selecciona 'PrestaShop' como plataforma"
echo "   - Ingresa la URL: https://100x100chef.com/shop"
echo "   - Ingresa la API Key: E5CUG6DLAD9EA46AIN7Z2LIX1W3IIJKZ"
echo "   - Guarda la conexión"
echo ""
echo "4️⃣  DESPUÉS de guardar la conexión:"
echo "   - Aparecerá el botón 'Escanear Productos'"
echo "   - Haz clic en ese botón"
echo "   - Espera a que escanee los productos"
echo "   - Revisa el preview y confirma la importación"
echo ""
echo "⚠️  IMPORTANTE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "El botón 'Escanear Productos' SOLO aparece cuando:"
echo "✅ Hay una conexión PrestaShop configurada"
echo "✅ La conexión tiene URL y API Key guardadas"
echo "✅ La conexión está visible en la lista"
echo ""
echo "🔍 SI NO VES EL BOTÓN:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Verifica que estás en la página CATÁLOGO"
echo "2. Verifica que has guardado la conexión PrestaShop"
echo "3. Verifica que la conexión tiene URL y API Key"
echo "4. Recarga la página si es necesario"
echo ""
echo "✅ UBICACIÓN EXACTA:"
echo "   Página: Catálogo > Sección: 'Conectar Ecommerce'"


