#!/bin/bash

echo "🔍 DIAGNÓSTICO DEL ERROR 502 DE PRESTASHOP"
echo ""
echo "El error 502 (Bad Gateway) puede tener varias causas:"
echo ""
echo "1️⃣  VERIFICAR QUE NETLIFY ESTÁ DESPLEGADO:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "El proxy de Netlify debe estar desplegado para funcionar."
echo ""
echo "Si NO estás usando Netlify, el proxy NO funcionará."
echo "En ese caso, necesitas:"
echo ""
echo "  Opción A: Desplegar en Netlify"
echo "    - Asegúrate de que netlify/functions/prestashop.js esté desplegado"
echo "    - La función debe estar disponible en: /api/prestashop/*"
echo ""
echo "  Opción B: Usar Supabase Edge Function (recomendado)"
echo "    - Crear una Edge Function similar en Supabase"
echo "    - Aprovecha que ya usas Supabase"
echo ""
echo "2️⃣  PROBAR CONEXIÓN DIRECTA (sin proxy):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Ejecuta: node test-prestashop-import.js"
echo "Esto probará la conexión directa con PrestaShop."
echo ""
echo "3️⃣  VERIFICAR URL Y CREDENCIALES:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "URL debe ser: https://100x100chef.com/shop"
echo "API Key: E5CUG6DLAD9EA46AIN7Z2LIX1W3IIJKZ"
echo ""
echo "4️⃣  SOLUCIÓN RÁPIDA - DESPLEGAR EN SUPABASE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Ya que usas Supabase, puedes crear una Edge Function"
echo "que haga lo mismo que el proxy de Netlify."
echo ""
echo "¿Quieres que cree una Edge Function en Supabase?"
echo "Esto sería más rápido y no necesitarías Netlify."


