#!/bin/bash

echo "❌ ERROR 404 DETECTADO"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "El error 404 significa que la Edge Function"
echo "'prestashop-proxy' NO está desplegada en Supabase"
echo ""
echo "✅ SOLUCIÓN: DESPLEGAR LA EDGE FUNCTION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 PASOS RÁPIDOS:"
echo ""
echo "1. Abre: https://supabase.com/dashboard/project/akwobmrcwqbbrdvzyiul/functions"
echo ""
echo "2. Haz clic en 'New Function'"
echo ""
echo "3. Nombre: prestashop-proxy"
echo ""
echo "4. Copia TODO el código de:"
echo "   supabase/functions/prestashop-proxy/index.ts"
echo ""
echo "5. Pégalo en el editor de Supabase"
echo ""
echo "6. Haz clic en 'Deploy'"
echo ""
echo "7. Espera a que diga 'Deployed' o 'Active'"
echo ""
echo "8. Vuelve a probar el botón 'Probar Conexión'"
echo ""
echo "📄 INSTRUCCIONES DETALLADAS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Abre: INSTRUCCIONES_DESPLIEGUE_PASO_A_PASO.md"
echo ""
echo "📁 ARCHIVO DEL CÓDIGO:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "supabase/functions/prestashop-proxy/index.ts"
echo ""
echo "✅ Después del despliegue, el error 404 desaparecerá"

