#!/bin/bash

echo "✅ SERVIDOR ESTÁ CORRIENDO"
echo ""
echo "📊 ESTADO ACTUAL:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Servidor respondiendo en: http://localhost:3000"
echo "✅ Proceso Vite activo"
echo ""
echo "🌐 ABRE EN TU NAVEGADOR:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "http://localhost:3000"
echo ""
echo "O específicamente para Catálogo:"
echo "http://localhost:3000/catalog"
echo ""
echo "🔧 SI LA PÁGINA NO CARGA:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Recarga la página (F5 o Ctrl+R)"
echo ""
echo "2. Limpia la caché del navegador:"
echo "   - Windows/Linux: Ctrl + Shift + R"
echo "   - Mac: Cmd + Shift + R"
echo ""
echo "3. Abre DevTools (F12) y revisa:"
echo "   - Pestaña Console: ¿Hay errores?"
echo "   - Pestaña Network: ¿Se están cargando los archivos?"
echo ""
echo "4. Verifica en la terminal:"
echo "   - ¿Ves algún error de compilación?"
echo "   - ¿Dice 'ready in XXX ms'?"
echo ""
echo "📋 SI SIGUE SIN FUNCIONAR:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Detén el servidor (Ctrl+C en la terminal)"
echo ""
echo "2. Reinicia el servidor:"
echo "   npm run dev"
echo ""
echo "3. Espera a ver:"
echo "   ➜  Local:   http://localhost:3000/"
echo ""
echo "4. Abre esa URL en el navegador"
echo ""
echo "✅ El servidor está funcionando correctamente"

