#!/bin/bash
# Script para subir cambios manualmente

echo "🚀 SUBIENDO CAMBIOS MANUALMENTE"
echo "==============================="
echo ""

echo "❌ PROBLEMA IDENTIFICADO:"
echo "El token de GitHub está expirado o no tiene permisos"
echo ""

echo "✅ SOLUCIONES DISPONIBLES:"
echo "==============================="
echo ""
echo "OPCIÓN 1: GitHub Desktop (MÁS FÁCIL)"
echo "1. Abrir GitHub Desktop"
echo "2. Ver los 3 commits pendientes:"
echo "   - 1583d16: Mejoras completas"
echo "   - 4673886: Fix límite 5MB"
echo "   - 9548ece: Layout 2 columnas"
echo "3. Hacer clic en 'Push origin'"
echo ""
echo "OPCIÓN 2: GitHub Web Interface"
echo "1. Ir a: https://github.com/TresPuntos/IA"
echo "2. Hacer clic en 'Upload files'"
echo "3. Subir archivos modificados:"
echo "   - src/App.tsx"
echo "   - src/lib/config.ts"
echo "   - src/lib/configStorage.ts"
echo "   - src/components/ModelParamsCard.tsx"
echo "   - src/components/ProductCatalogCard.tsx"
echo "   - src/lib/productCatalog.ts"
echo "   - src/lib/supabaseChat.ts"
echo "   - supabase/functions/openai-chat/index.ts"
echo ""
echo "OPCIÓN 3: Nuevo token de GitHub"
echo "1. Ir a: https://github.com/settings/tokens"
echo "2. Crear nuevo token con permisos 'repo' y 'workflow'"
echo "3. Ejecutar: git push https://NUEVO_TOKEN@github.com/TresPuntos/IA.git main"
echo ""
echo "OPCIÓN 4: SSH (si tienes configurado)"
echo "1. Cambiar remote a SSH: git remote set-url origin git@github.com:TresPuntos/IA.git"
echo "2. Ejecutar: git push origin main"
echo ""
echo "🎯 CAMBIOS PENDIENTES:"
echo "==============================="
echo "• Layout con cajas de 500px máximo"
echo "• Selector de modelo OpenAI"
echo "• Tag de conexión en tiempo real"
echo "• Botones de eliminación de productos"
echo "• Guardado mejorado de configuración"
echo "• Límite de 5MB para archivos"
echo "• Manejo mejorado de PDFs"
echo ""
echo "⏱️  Una vez subido: 2-3 minutos para desplegar en Netlify"
echo "🌐 URL: https://stalwart-panda-77e3cb.netlify.app/"
